#Ejercicios de práctica - NumPy y pandas
20AGO 2026

## Importar la biblioteca
Complete la importación con el alias convencional de la comunidad.

In [6]:
import numpy as np
print(np.__version__) # sin la _versión muestra la ruta

2.0.2

##2. Del listado al arreglo
Convierta la lista de precios en un arreglo de NumPy.

In [10]:
precios = np.array([24000, 28000, 22000, 30000, 8000])
print(type(precios).__name__)
print(precios.dtype)

ndarray
int64

##3. Los tres atributos
Averigüe la forma, el número de dimensiones y la cantidad de elementos.

In [13]:
matriz = np.array([[2, 24000],
 [1, 28000],
 [3, 22000]])
print(matriz.shape) # forma
print(matriz.ndim) # dimensiones
print(matriz.size) # total de elementos

(3, 2)
2
6

##4.  Secuencias automáticas
Genere una secuencia con paso fijo, otra con extremos fijos y un arreglo de ceros.

In [15]:
secuencia = np.arange(0, 10, 2)
rango = np.linspace(0, 1, 5)
ceros = np.zeros(5)
print(secuencia)
print(rango)
print(ceros.dtype)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
float64

##5.  Corrección: falta algo
Este bloque lanza TypeError: array() takes from 1 to 2 positional arguments but 3 were given.

In [19]:
# precios = np.array(24000, 28000, 22000), esta línea genera error debido a que hacen falta lo [], que indican que es un arreglo

precios = np.array([24000, 28000, 22000])
print (precios) # agregué esta línea

[24000 28000 22000]

# Vectorización y broadcasting
Operar sobre el arreglo completo, sin escribir un solo ciclo

##6. Multiplicar dos arreglos
Calcule el ingreso de cada transacción multiplicando elemento por elemento.

In [20]:
cantidades = np.array([2, 1, 3, 2, 1])
precios = np.array([24000, 28000, 22000, 30000, 8000])
ingresos = cantidades * precios # Se agregó el signo de multiplicación
print(ingresos)

[48000 28000 66000 60000  8000]

##7. El escalar se estira
Aplique un descuento del diez por ciento a todos los precios.

In [22]:
con_descuento = precios * 0.9
print(con_descuento)
print(con_descuento.dtype)

[21600. 25200. 19800. 27000.  7200.]
float64

##8. El mismo cálculo, dos formas
Escriba con NumPy lo que el ciclo hace con listas.

In [31]:
# con listas de Python
lista = [24000, 28000, 22000, 30000, 8000]
resultado = []
for p in lista:
 resultado.append(p * 1.19)
print(resultado)
# con NumPy, en una sola línea
resultado_np = precios * 1.19
print(resultado_np)

[28560.0, 33320.0, 26180.0, 35700.0, 9520.0]

##9. Predicción: lista o arreglo Intermedio
El mismo operador sobre dos estructuras distintas.

In [34]:
lista = [1, 2, 3]
arreglo = np.array([1, 2, 3])
print(lista * 2) # duplica los valores de la lista 2 veces
print(arreglo * 2) # multiplica * 2 cada valor del array

[1, 2, 3, 1, 2, 3]
[2 4 6]

##10. Predicción: formas distintas
Un arreglo de cinco elementos multiplicado por uno de cuatro.

In [42]:
a = np.array([2, 1, 3, 2, 5])
b = np.array([10, 20, 30, 40, 5])
print(a * b)

# En la multiplicación de 5 x 4 genera error

[20 20 90 80 25]

## 11. Corrección: el ciclo sobra
El bloque funciona, pero desaprovecha NumPy por completo.

In [49]:
# Sin optimizar
ingresos1 = np.zeros(5)
for i in range(5):
 ingresos1[i] = cantidades[i] * precios[i]
print (ingresos1)

 #optimizado con np
ingresos = cantidades * precios
print (ingresos)

[48000 28000 66000 60000  8000]

#Indexación, rebanado y máscaras
Seleccionar por posición y, sobre todo, seleccionar por condición.
## 12. Primero, último y una porción
Obtenga elementos por posición sin contar cuántos hay.

In [52]:
print(precios)
print(precios[0]) # el primero
print(precios[-1]) # el último
print(precios[0:3]) # las posiciones 1, 2 y 3

[24000 28000 22000 30000  8000]
24000
8000
[24000 28000 22000]

13. La máscara booleana
Construya la condición y úsela para filtrar.

In [57]:
mascara = precios > 20000
print(mascara)
print(precios[mascara])
print(precios[mascara].sum())

[ True  True  True  True False]
[24000 28000 22000 30000]
104000

##14. Dos condiciones a la vez
Precios mayores a 10.000 y menores a 29.000. Recuerde el operador correcto.

In [58]:
seleccion = precios[(precios > 10000) & (precios < 29000)]
print(seleccion)

[24000 28000 22000]

##15. Etiquetar según una condición
Clasifique cada precio sin escribir un ciclo ni un if

In [60]:
etiquetas = np.where(precios > 25000, "alto", "normal")
print(etiquetas)
print (precios) #agrego este print para comprobar

['normal' 'alto' 'normal' 'alto' 'normal']
[24000 28000 22000 30000  8000]

##16. Contar y sumar lo filtrado
Cuántos elementos cumplen la condición y cuánto suman.

In [69]:
caros = precios[precios > 20000]
print(caros.size) # cuántos son
print(caros.sum()) # cuánto suman

4
104000

##17. Corrección: el operador equivocado
Este bloque lanza ValueError: The truth value of an array with more than one element is ambiguous.

In [71]:
seleccion = precios[(precios > 10000) & (precios < 29000)]
print (seleccion)

[24000 28000 22000]

# Agregar y resumir
Reducir muchos valores a uno, sobre todo el arreglo o a lo largo de un eje.

##18. Las funciones de resumen
Complete cada línea con el método que corresponde.

In [73]:
ingresos = np.array([48000, 28000, 66000, 60000, 8000])
print(ingresos.sum()) # 210000
print(ingresos.mean()) # 42000.0
print(ingresos.max()) # 66000
print(round(ingresos.std(), 2))

210000
42000.0
66000
21391.59

##19. Sumar por columna
Cada fila es un producto y cada columna una sede. Obtenga el total de cada sede.

In [75]:
matriz = np.array([[48000, 28000],
 [66000, 60000],
 [ 8000, 12000]])
print(matriz.sum(axis=0))

[122000 100000]

##20. Sumar por fila y en total
Ahora el total de cada producto y el total general.

In [77]:
print(matriz.sum(axis=1))
print(matriz.sum())

[ 76000 126000  20000]
222000

##21. Predicción: el eje que confunde
Sin ejecutar nada todavía, escriba su predicción y después compruébela.

In [78]:
print(matriz.mean(axis=0))

[40666.66666667 33333.33333333]

#E. Del arreglo a la tabla
El arreglo resuelve el cálculo; el DataFrame le pone nombre a las columnas.

##Crear e inspeccionar el DataFrame
Convierta la lista de diccionarios del caso en una tabla y revise su estructura.

In [88]:
datos_ventas = {"fecha": ["3/08/2026", "3/08/2026", "4/08/2026"],
           "cliente_ID": [101, 102, 103],
           "producto": ["Bowl Andino", "Pasta Urbana", "Bowl Andino"],
           "categoría": ["Almuerzo", "Almuerzo", "Almuerzo"],
           "cantidad": [2, 1, 1],
           "precio Unitario": [24000, 28000, 22000],
           "costo Unitario": [14000, 17000, 24000],
           "sede": ["Centro", "Norte", "Centro"]}

print (datos_ventas)

{'fecha': ['3/08/2026', '3/08/2026', '4/08/2026'], 'cliente_ID': [101, 102, 103], 'producto': ['Bowl Andino', 'Pasta Urbana', 'Bowl Andino'], 'categoría': ['Almuerzo', 'Almuerzo', 'Almuerzo'], 'cantidad': [2, 1, 1], 'precio Unitario': [24000, 28000, 22000], 'costo Unitario': [14000, 17000, 24000], 'sede': ['Centro', 'Norte', 'Centro']}

In [89]:
import pandas as pd
df_ventas = pd.DataFrame(datos_ventas)
df_ventas["fecha"] = pd.to_datetime(df_ventas["fecha"])
print(df_ventas.shape) # forma de la tabla
print(df_ventas.head(3)) # primeras tres filas

(3, 8)
       fecha  cliente_ID      producto categoría  cantidad  precio Unitario  \
0 2026-03-08         101   Bowl Andino  Almuerzo         2            24000
1 2026-03-08         102  Pasta Urbana  Almuerzo         1            28000
2 2026-04-08         103   Bowl Andino  Almuerzo         1            22000

   costo Unitario    sede
0           14000  Centro
1           17000   Norte
2           24000  Centro

##CARGAR ARCHIVO CSV

In [94]:
import pandas as pd

df_ventas=pd.read_csv ("datos_ventas.csv")
df_ventas.head()

                                                          fecha;cliente;producto;categoria;cantidad;precio_unitario;costo_unitario;sede
3/08/2026;101;Bowl Andino;Almuerzo;2;24.000     00;14.000                                          00;centro
3/08/2026;102;Pasta Urbana;Almuerzo;1;28.000    00;17.000                                           00;NORTE
4/08/2026;103;Bowl Andino;Almuerzo;1;24.000     00;14.000                                         00;Centro
                                                00;14.000                                         00;Centro
4/08/2026;104;Hamburguesa Central;Cena;2;30.000 00;19.000                                           00;Norte

In [95]:
##Conversión de fecha

# La columna 'fecha' no existe debido a que el CSV no se leyó correctamente.
# El archivo 'datos_ventas.csv' parece usar ';' como separador, no ',' (el valor por defecto).
# Primero, corregimos la lectura del CSV en la celda 'pebf5ykV9q4a'.
# Después de eso, esta línea debería funcionar sin cambios, asumiendo que 'fecha' es el nombre de la columna deseada.
df_ventas["fecha"] = pd.to_datetime(df_ventas["fecha"], format="mixed")
df_ventas.head()

KeyError: 'fecha'

In [96]:
df = pd.read_csv ("/content/drive/MyDrive/Maestria/Programación Python/Data/datos_ventas.csv")
df.head()

                                                          fecha;cliente;producto;categoria;cantidad;precio_unitario;costo_unitario;sede
3/08/2026;101;Bowl Andino;Almuerzo;2;24.000     00;14.000                                          00;centro
3/08/2026;102;Pasta Urbana;Almuerzo;1;28.000    00;17.000                                           00;NORTE
4/08/2026;103;Bowl Andino;Almuerzo;1;24.000     00;14.000                                         00;Centro
                                                00;14.000                                         00;Centro
4/08/2026;104;Hamburguesa Central;Cena;2;30.000 00;19.000                                           00;Norte